"""Assembles complete CalculiX input decks from Gmsh-generated mesh files."""
from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Material library: name -> (density kg/m3, E Pa, poisson, yield MPa)
# ---------------------------------------------------------------------------
COMPONENT_MATERIALS: dict[str, dict[str, float]] = {
    "Al-7075": {
        "density": 2810.0,
        "youngs_modulus": 71.7e9,
        "poisson": 0.33,
        "yield_strength": 503.0e6,
    },
    "FR4": {
        "density": 1850.0,
        "youngs_modulus": 22.0e9,
        "poisson": 0.12,
        "yield_strength": 310.0e6,
    },
    "Battery": {
        "density": 2500.0,
        "youngs_modulus": 10.0e9,
        "poisson": 0.30,
        "yield_strength": 50.0e6,
    },
}

# Default mapping from component type keywords to material names.  The writer
# will try to match each elset name against these keywords (case-insensitive).
_DEFAULT_ELSET_MATERIAL_MAP: dict[str, str] = {
    "frame": "Al-7075",
    "rail": "Al-7075",
    "panel": "Al-7075",
    "structure": "Al-7075",
    "bracket": "Al-7075",
    "pcb": "FR4",
    "board": "FR4",
    "battery": "Battery",
    "cell": "Battery",
}


@dataclass
class CalculixInput:
    """Reference to a written CalculiX input deck."""

    inp_file: str
    job_name: str


class CalculixInputWriter:
    """Writes complete CalculiX input decks that *INCLUDE a Gmsh mesh .inp.

    The Gmsh mesh .inp is expected to contain ``*NODE``, ``*ELEMENT``, and
    ``*ELSET`` blocks.  This writer reads node coordinates from that file to
    identify bottom-face nodes (z ~ 0), then emits a new .inp that includes the
    mesh, material definitions, section assignments, boundary conditions and
    analysis steps.
    """

    def __init__(
        self,
        mesh_inp_path: str,
        component_elsets: dict[str, str],
    ) -> None:
        """Initialise the writer.

        Args:
            mesh_inp_path: Path to the Gmsh-exported .inp that contains nodes,
                elements and elset definitions.
            component_elsets: Mapping of *component_id* to the elset name
                defined inside the Gmsh .inp.  The elset name will be matched
                against ``_DEFAULT_ELSET_MATERIAL_MAP`` (or the component_id
                itself) to select a material.
        """
        self._mesh_path = Path(mesh_inp_path)
        self._component_elsets = component_elsets

        if not self._mesh_path.exists():
            raise FileNotFoundError(
                f"Mesh .inp not found: {self._mesh_path}"
            )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write_static_analysis(
        self,
        output_dir: Path,
        job_name: str = "cubesat_static",
    ) -> CalculixInput:
        """Create a complete CalculiX static analysis input deck.

        The deck contains two load steps:
          1. 10 g axial (negative Z) quasi-static launch load.
          2. 5 g lateral (positive X) quasi-static launch load.

        Args:
            output_dir: Directory to write the assembled .inp file into.
            job_name: Base name for the CalculiX job (without extension).

        Returns:
            A ``CalculixInput`` with the path and job name.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        out_path = output_dir / f"{job_name}.inp"

        nodes = self._parse_nodes()
        bottom_node_ids = self._find_bottom_face_nodes(nodes)

        if not bottom_node_ids:
            logger.warning(
                "No bottom-face nodes found (z~0). Boundary conditions will "
                "be empty -- the solve will likely be singular."
            )

        elset_material = self._resolve_materials()

        lines: list[str] = []
        lines.append(f"** CalculiX static analysis deck generated by sat-maestro")
        lines.append(f"** Mesh file: {self._mesh_path.name}")
        lines.append("**")

        # Include the mesh
        lines.append(f"*INCLUDE, INPUT={self._mesh_path.name}")
        lines.append("**")

        # Bottom-face node set
        lines.append("** -----------------------------------------------")
        lines.append("** Node sets")
        lines.append("** -----------------------------------------------")
        lines.extend(self._format_nset("NSET_BOTTOM", bottom_node_ids))
        lines.append("**")

        # Materials
        lines.append("** -----------------------------------------------")
        lines.append("** Materials")
        lines.append("** -----------------------------------------------")
        lines.extend(self._format_materials())
        lines.append("**")

        # Solid sections
        lines.append("** -----------------------------------------------")
        lines.append("** Sections")
        lines.append("** -----------------------------------------------")
        lines.extend(self._format_sections(elset_material))
        lines.append("**")

        # Boundary conditions -- fix all 6 DOF on bottom face
        lines.append("** -----------------------------------------------")
        lines.append("** Boundary conditions")
        lines.append("** -----------------------------------------------")
        lines.append("*BOUNDARY")
        lines.append("NSET_BOTTOM, 1, 6, 0.0")
        lines.append("**")

        # Step 1: 10 g axial (Z, downward = -1 direction)
        lines.append("** -----------------------------------------------")
        lines.append("** Step 1: 10 g axial quasi-static launch load (Z)")
        lines.append("** -----------------------------------------------")
        lines.append("*STEP")
        lines.append("*STATIC")
        lines.append("*DLOAD")
        lines.append("Eall, GRAV, 98.1, 0., 0., -1.")
        lines.append("**")
        lines.append("*NODE FILE")
        lines.append("U")
        lines.append("*EL FILE")
        lines.append("S")
        lines.append("*NODE PRINT, NSET=NSET_BOTTOM")
        lines.append("U")
        lines.append("*EL PRINT, ELSET=Eall")
        lines.append("S")
        lines.append("*END STEP")
        lines.append("**")

        # Step 2: 5 g lateral (X)
        lines.append("** -----------------------------------------------")
        lines.append("** Step 2: 5 g lateral quasi-static launch load (X)")
        lines.append("** -----------------------------------------------")
        lines.append("*STEP")
        lines.append("*STATIC")
        lines.append("*DLOAD")
        lines.append("Eall, GRAV, 49.05, 1., 0., 0.")
        lines.append("**")
        lines.append("*NODE FILE")
        lines.append("U")
        lines.append("*EL FILE")
        lines.append("S")
        lines.append("*NODE PRINT, NSET=NSET_BOTTOM")
        lines.append("U")
        lines.append("*EL PRINT, ELSET=Eall")
        lines.append("S")
        lines.append("*END STEP")

        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Wrote static analysis deck: %s", out_path)

        return CalculixInput(inp_file=str(out_path), job_name=job_name)

    def write_modal_analysis(
        self,
        output_dir: Path,
        job_name: str = "cubesat_modal",
        num_modes: int = 20,
    ) -> CalculixInput:
        """Create a CalculiX modal (frequency) analysis input deck.

        Args:
            output_dir: Directory to write the assembled .inp file into.
            job_name: Base name for the CalculiX job (without extension).
            num_modes: Number of eigenfrequencies to extract.

        Returns:
            A ``CalculixInput`` with the path and job name.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        out_path = output_dir / f"{job_name}.inp"

        nodes = self._parse_nodes()
        bottom_node_ids = self._find_bottom_face_nodes(nodes)

        if not bottom_node_ids:
            logger.warning(
                "No bottom-face nodes found (z~0). Boundary conditions will "
                "be empty -- modal solve may fail."
            )

        elset_material = self._resolve_materials()

        lines: list[str] = []
        lines.append("** CalculiX modal analysis deck generated by sat-maestro")
        lines.append(f"** Mesh file: {self._mesh_path.name}")
        lines.append("**")

        # Include mesh
        lines.append(f"*INCLUDE, INPUT={self._mesh_path.name}")
        lines.append("**")

        # Bottom-face node set
        lines.append("** -----------------------------------------------")
        lines.append("** Node sets")
        lines.append("** -----------------------------------------------")
        lines.extend(self._format_nset("NSET_BOTTOM", bottom_node_ids))
        lines.append("**")

        # Materials
        lines.append("** -----------------------------------------------")
        lines.append("** Materials")
        lines.append("** -----------------------------------------------")
        lines.extend(self._format_materials())
        lines.append("**")

        # Solid sections
        lines.append("** -----------------------------------------------")
        lines.append("** Sections")
        lines.append("** -----------------------------------------------")
        lines.extend(self._format_sections(elset_material))
        lines.append("**")

        # Boundary conditions
        lines.append("** -----------------------------------------------")
        lines.append("** Boundary conditions")
        lines.append("** -----------------------------------------------")
        lines.append("*BOUNDARY")
        lines.append("NSET_BOTTOM, 1, 6, 0.0")
        lines.append("**")

        # Frequency step
        lines.append("** -----------------------------------------------")
        lines.append(f"** Frequency analysis: {num_modes} modes")
        lines.append("** -----------------------------------------------")
        lines.append("*STEP")
        lines.append(f"*FREQUENCY")
        lines.append(f"{num_modes}")
        lines.append("**")
        lines.append("*NODE FILE")
        lines.append("U")
        lines.append("*EL FILE")
        lines.append("S")
        lines.append("*NODE PRINT, NSET=Nall, FREQUENCY=1")
        lines.append("U")
        lines.append("*END STEP")

        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Wrote modal analysis deck: %s", out_path)

        return CalculixInput(inp_file=str(out_path), job_name=job_name)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _parse_nodes(self) -> dict[int, tuple[float, float, float]]:
        """Read node coordinates from the Gmsh mesh .inp.

        Returns:
            Mapping of node_id -> (x, y, z).
        """
        nodes: dict[int, tuple[float, float, float]] = {}
        in_node_block = False
        content = self._mesh_path.read_text(encoding="utf-8", errors="replace")

        for line in content.splitlines():
            stripped = line.strip()

            if stripped.upper().startswith("*NODE"):
                in_node_block = True
                continue

            # Any new keyword terminates the current block
            if stripped.startswith("*") and in_node_block:
                in_node_block = False

            if in_node_block:
                parts = stripped.split(",")
                if len(parts) >= 4:
                    try:
                        nid = int(parts[0].strip())
                        x = float(parts[1].strip())
                        y = float(parts[2].strip())
                        z = float(parts[3].strip())
                        nodes[nid] = (x, y, z)
                    except (ValueError, IndexError):
                        continue

        logger.debug("Parsed %d nodes from mesh .inp", len(nodes))
        return nodes

    def _find_bottom_face_nodes(
        self,
        nodes: dict[int, tuple[float, float, float]],
        z_tolerance: float = 1.0e-3,
    ) -> list[int]:
        """Identify nodes that lie on the bottom face (z ~ z_min).

        Args:
            nodes: Node coordinate map.
            z_tolerance: Absolute tolerance in the same length unit as the
                mesh (typically millimetres) for identifying bottom-face nodes.

        Returns:
            Sorted list of node IDs on the bottom face.
        """
        if not nodes:
            return []

        z_min = min(z for _, _, z in nodes.values())

        bottom_ids = sorted(
            nid
            for nid, (_, _, z) in nodes.items()
            if abs(z - z_min) <= z_tolerance
        )
        logger.debug(
            "Found %d bottom-face nodes (z_min=%.4f, tol=%.4f)",
            len(bottom_ids),
            z_min,
            z_tolerance,
        )
        return bottom_ids

    def _resolve_materials(self) -> dict[str, str]:
        """Map each elset to a material name.

        Uses ``component_elsets`` values (elset names) and tries to match them
        against ``_DEFAULT_ELSET_MATERIAL_MAP`` keywords.  Falls back to
        ``Al-7075`` if no keyword matches.

        Returns:
            Mapping of elset_name -> material_name.
        """
        result: dict[str, str] = {}

        for component_id, elset_name in self._component_elsets.items():
            material = self._match_material(component_id, elset_name)
            result[elset_name] = material

        return result

    @staticmethod
    def _match_material(component_id: str, elset_name: str) -> str:
        """Try to match a component/elset to a material via keywords."""
        for keyword, mat_name in _DEFAULT_ELSET_MATERIAL_MAP.items():
            if keyword in component_id.lower() or keyword in elset_name.lower():
                return mat_name
        # Default to aluminium alloy if nothing matches
        return "Al-7075"

    @staticmethod
    def _format_nset(name: str, node_ids: list[int], cols: int = 10) -> list[str]:
        """Format a *NSET block with wrapped node IDs.

        Args:
            name: Name of the node set.
            node_ids: Node IDs to include.
            cols: Maximum number of IDs per line.

        Returns:
            List of lines composing the *NSET block.
        """
        lines: list[str] = [f"*NSET, NSET={name}"]
        for i in range(0, len(node_ids), cols):
            chunk = node_ids[i : i + cols]
            line = ", ".join(str(n) for n in chunk)
            # Trailing comma except on the last line
            if i + cols < len(node_ids):
                line += ","
            lines.append(line)
        return lines

    @staticmethod
    def _format_materials() -> list[str]:
        """Generate *MATERIAL blocks for all materials in the library."""
        lines: list[str] = []
        for mat_name, props in COMPONENT_MATERIALS.items():
            ccx_name = mat_name.replace("-", "").replace(" ", "_").upper()
            lines.append(f"*MATERIAL, NAME={ccx_name}")
            lines.append("*ELASTIC")
            lines.append(f"{props['youngs_modulus']:.1f}, {props['poisson']}")
            lines.append("*DENSITY")
            lines.append(f"{props['density']:.1f}")
            lines.append("**")
        return lines

    @staticmethod
    def _format_sections(elset_material: dict[str, str]) -> list[str]:
        """Generate *SOLID SECTION blocks mapping elsets to materials.

        Args:
            elset_material: Mapping of elset name -> material name.
        """
        lines: list[str] = []
        for elset_name, mat_name in elset_material.items():
            ccx_mat = mat_name.replace("-", "").replace(" ", "_").upper()
            lines.append(
                f"*SOLID SECTION, ELSET={elset_name}, MATERIAL={ccx_mat}"
            )
            lines.append("**")
        return lines
